### ISSUE TITLE
support multiple function

### ISSUE THREAD

**Issue by coderhglee** [awslabs/serverless-plugin-lambda-insights#24] opened 2022-03-30 07:31 UTC
## Description
When multiple serverless functions are declared, insight layer is not created from next function when a function that does disabled lambdaInsights is included

```
      functions: {
        myFunction: {
          lambdaInsights: false,
          handler: 'handler.hello',
        },
        myFunction2: {
          lambdaInsights: true,
          handler: 'handler.hello',
        },
      },
```

myFunction2.layers is not defined `LambdaInsightsExtension`

## Proposed change

https://github.com/awslabs/serverless-plugin-lambda-insights/blob/15521fcd9179b79170591b1701e6b753b38a59e7/index.js#L161

use `continue;` instead of `return;`

**Comment by iriskraja77** [comment] 2022-04-12 17:33
Thanks @coderhglee the issue is now fixed.

**Closed by iriskraja77** 2022-04-12 17:33 UTC

**Comment by coderhglee** [comment] 2022-04-13 02:05
Thanks a lot @iriskraja77
